/**
 * api Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 6
 * Cost Function Score: 639.0
 */

// Core exports
export { apiProvider } from './apiProvider';
export { index.d } from './index.d';


// IoC Configuration
export { apiProvider, apiProviderImpl } from './apiProvider';

// Type definitions
export type { index.d } from './index.d';


export default {
  moduleName: "core/api",
  priority: 6,
  costScore: 639.0,
  dependencies: []
};
