/**
 * dop Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 3
 * Cost Function Score: 351.0
 */

// Core exports
export { dopProvider } from './dopProvider';
export { index.d } from './index.d';


// IoC Configuration
export { dopProvider, dopProviderImpl } from './dopProvider';

// Type definitions
export type { index.d } from './index.d';


export default {
  moduleName: "core/dop",
  priority: 3,
  costScore: 351.0,
  dependencies: []
};
