/**
 * parser Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 5
 * Cost Function Score: 550.0
 */

// Core exports
export { index.d } from './index.d';
export { parserProvider } from './parserProvider';


// IoC Configuration
export { parserProvider, parserProviderImpl } from './parserProvider';

// Type definitions
export type { index.d } from './index.d';


export default {
  moduleName: "core/parser",
  priority: 5,
  costScore: 550.0,
  dependencies: []
};
