
=======
/**
 * cli Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 9
 * Cost Function Score: 929.0
 */

// Core exports
export { cliProvider } from './cliProvider';
export { main } from './main';


// IoC Configuration
export { cliProvider, cliProviderImpl } from './cliProvider';

// Type definitions


export default {
  moduleName: "cli",
  priority: 9,
  costScore: 929.0,
  dependencies: []
};
