/**
 * validation Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 4
 * Cost Function Score: 435.0
 */

// Core exports
export { validationProvider } from './validationProvider';


// IoC Configuration
export { validationProvider, validationProviderImpl } from './validationProvider';

// Type definitions


export default {
  moduleName: "core/validation",
  priority: 4,
  costScore: 435.0,
  dependencies: []
};
