/**
 * automaton Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 2
 * Cost Function Score: 223.0
 */

// Core exports
export { automatonProvider } from './automatonProvider';


// IoC Configuration
export { automatonProvider, automatonProviderImpl } from './automatonProvider';

// Type definitions


export default {
  moduleName: "core/automaton",
  priority: 2,
  costScore: 223.0,
  dependencies: []
};
