/**
 * common Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 1
 * Cost Function Score: 118.0
 */

// Core exports
export { commonProvider } from './commonProvider';


// IoC Configuration
export { commonProvider, commonProviderImpl } from './commonProvider';

// Type definitions


export default {
  moduleName: "core/common",
  priority: 1,
  costScore: 118.0,
  dependencies: []
};
