/**
 * api Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 6
 * Cost Function Score: 639.0
 */

// Core exports
export { apiProvider } from './apiProvider';


// IoC Configuration
export { apiProvider, apiProviderImpl } from './apiProvider';

// Type definitions


export default {
  moduleName: "core/api",
  priority: 6,
  costScore: 639.0,
  dependencies: []
};
