/**
 * ast Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 7
 * Cost Function Score: 727.0
 */

// Core exports
export { astProvider } from './astProvider';


// IoC Configuration
export { astProvider, astProviderImpl } from './astProvider';

// Type definitions


export default {
  moduleName: "core/ast",
  priority: 7,
  costScore: 727.0,
  dependencies: []
};
