/**
 * ioc Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 8
 * Cost Function Score: 816.0
 */

// Core exports
export { iocProvider } from './iocProvider';


// IoC Configuration
export { iocProvider, iocProviderImpl } from './iocProvider';

// Type definitions


export default {
  moduleName: "core/ioc",
  priority: 8,
  costScore: 816.0,
  dependencies: []
};
