/**
 * policy Module Index
 * Generated by OBIX Framework Refactoring Script
 * Priority Level: 10
 * Cost Function Score: 1046.0
 */

// Core exports
export { PolicyDecorator } from './PolicyDecorator';
export { policyProvider } from './policyProvider';


// IoC Configuration
export { policyProvider, policyProviderImpl } from './policyProvider';

// Type definitions


export default {
  moduleName: "core/policy",
  priority: 10,
  costScore: 1046.0,
  dependencies: []
};
